# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "013186329397-terragrunt-state"
    encrypt      = true
    key          = "lambdas/./terraform.tfstate"
    region       = "eu-central-1"
    use_lockfile = true
  }
}
